version: '3.8'

services:
  backend:
    build: .
    container_name: donation-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    container_name: donation-redis
    ports:
      - "6379:6379"